---
driver:
  name: vagrant
  customize:
    memory: 256

provisioner:
  name: chef_zero
  attributes:
    zookeeperd:
      cluster:
        auto_discovery: false
      config:
        client_port: 9000

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: client
    run_list:
      - recipe[zookeeperd]
  - name: server
    excludes:
      - centos-6.5
      - centos-7.1
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        cloudera_repo: false
  - name: server-cloudera
    run_list:
      - recipe[zookeeperd::server]
  - name: server-jar
    run_list:
      - recipe[zookeeperd::server]
    attributes:
      zookeeperd:
        install:
          method: 'jar'
