#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'zookeeperd', path: '.'
cookbook 'teapot-handler', :git => 'https://github.com/hw-labs/teapot-handler-cookbook.git'
